workers = 2
threads = 2
bind = "127.0.0.1:3000"
pidfile = "gunicorn.pid"
accesslog = "gunicorn_access.log"
errorlog = "gunicorn_error.log"
pythonpath = "/Users/wzx/miniconda3/envs/server/bin/python"
loglevel = "info"
reload = True
data_path = "./data/"
src_path = "./"
db_path = "./data/db.sqlite"
key_tags = ["AT", "UT", "AT_wide", "UT_wide"]
map_tags = {"Ongoing": "Status"}
idle_tags = []
